9.nc news
OlliePatty/fe-nc-news pull request #5
Opened 2023-07-18 15:01 UTC by OlliePatty

2023-07-18 15:38 UTC, Beth-McCormack requested changes
I've left a comment in your code, please have a look and submit another PR when this is done 🙂

2023-07-18 15:38 UTC, Beth-McCormack commented on src/components/Home.jsx
>        {articles.map((article)=>{
Filtering by topic should not be done on the front end, but by utilising back end queries. Have a look at the NC notes on axios for some pointers on this🙂

2023-07-19 08:09 UTC, NRMSMITH requested changes
Have a look over your set Errors :) (good work on making the api do the work!)

2023-07-19 08:09 UTC, NRMSMITH commented on src/components/ArticlesList.jsx
> +  useEffect(()=>{
I would suggest that you should reset your error to null here :)

2023-07-19 08:09 UTC, NRMSMITH commented on src/components/Topics.jsx
> +    useEffect(()=>{
where is set Error established here?

2023-07-19 09:35 UTC, xViolaine approved these changes

2023-07-19 09:35 UTC, xViolaine commented on src/components/Topics.jsx
> +  loading ? <p className='loading'>Loading</p> : (
Good job taking the feedback given to you on board! Just a small note; nested ternaries get confusing quickly. This is still mostly alright, but anything more than that, and I would recommend a different way to go about this :D

2023-07-19 09:38 UTC, merged